version: "3.8"

services:
  my_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: product_db
    networks:
      - lab2
    ports:
      - "3307:3306"

  my_node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - lab2

networks:
  lab2:
    driver: bridge
