version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    user: "rabbitmq"
    command: sh -c "chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie && chmod 400 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - lab2_lab2

  manager:
    build:
      context: ./manager
    ports:
      - "4000"
      - "41234/udp"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
    volumes:
      - ./manager:/index
    command: ["sh", "-c", "node index.js"]
    networks:
      - lab2_lab2

  smtp-service:
    build:
      context: ./smtp
      dockerfile: Dockerfile
    container_name: smtp-email-service
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  lab2_lab2:
    external: true
